distributable:
  url: https://github.com/google/sentencepiece/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: google/sentencepiece/releases/tags
  ignore: '1.0.0' # whoops, who tagged this then?

dependencies:
  linux:
    # error: no matching function for call to 'atomic_fetch_add' with llvm
    # needs libstdc++
    gnu.org/gcc: '*'

build:
  dependencies:
    cmake.org: ^3
    python.org: ~3.11
    pip.pypa.io: '*'
    freedesktop.org/pkg-config: ~0.29
  working-directory: build
  script:
    # this is not a fix; this is a test
    - run: sed -i 's/\+brewing//g' *.py
      working-directory: ${{deps.python.org.prefix}}/lib/python3.11
    - cmake .. $CMAKE_ARGS
    - make --jobs {{ hw.concurrency }} install

    - pip install ../python --verbose  --prefix="{{prefix}}"
  env:
    CMAKE_ARGS:
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DCMAKE_BUILD_TYPE=Release
    # FIXME: for some reason, only linux/x86-64 is finding the build dir instead of the final prefix...
    linux/x86-64:
      CMAKE_ARGS:
        - -DCMAKE_CXX_FLAGS=-L{{deps.python.org.prefix}}/lib

provides:
  - bin/spm_decode
  - bin/spm_encode
  - bin/spm_export_vocab
  - bin/spm_normalize
  - bin/spm_train

runtime:
  env:
    PYTHONPATH: '{{prefix}}/lib/python3.11/site-packages'

test:
  dependencies:
    gnu.org/wget: '*'
    python.org: ~3.11
  script: |
    wget https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt
    spm_train --input=botchan.txt --model_prefix=m --vocab_size=1000

    python -c 'import sentencepiece as spm; spm.SentencePieceProcessor()'
